name: Deploy to WF 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Generate PDF
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - name: Lint
        run: "npm run lint"
      - name: Build
        run: "npm run build"
      - uses: browser-actions/setup-chrome@v1
      - run: cp ./.output/public/_ipx/_/* ./.output/public/
      - run: >
          sed -i -e 's/\/_ipx\/_\/\([^\s"]*\)/.\/\1/g' ./.output/public/index.html
      - run: chrome --headless --print-to-pdf=./out.pdf ./.output/public/index.html
      - name: Archive resume
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: out.pdf
